//因为加了 emoji 所以就不用脚本维护了……会出 bug
(function(win){
	win.tags_chinese={}; win.tags_val={};
	win.tags_chinese['combinatorics'] = 'Σ组合数学Σ';
	win.tags_chinese['generating-function'] = '生成函数';
	win.tags_chinese['lagrange-inversion'] = '拉格朗日反演';
	win.tags_chinese['polynomial'] = 'x多项式x';
	win.tags_chinese['number-theory'] = '🐢数论🐢';
	win.tags_chinese['min25-sieve'] = 'min25筛';
	win.tags_chinese['calculating-geometry'] = '📏计算几何📏';
	win.tags_chinese['lagrange-interpolation'] = '拉格朗日插值';
	win.tags_chinese['linear-algebra'] = '线性代数';
	win.tags_chinese['string'] = '字符串';
	win.tags_chinese['lyndon-tech'] = 'lyndon 科技';
	win.tags_chinese['linear-programming'] = '线性规划';
	win.tags_chinese['group-counting'] = '🎨群论计数🎨';
	win.tags_chinese['game-theory'] = '♦博弈论♦';
	win.tags_chinese['set-power-series'] = '集合幂级数';
	win.tags_chinese['pigeon'] = '🕊鸽掉的文章🕊';
	win.tags_chinese['young-tableau'] = '杨表';
	win.tags_chinese['isotonic-regression'] = '保序回归';
	win.tags_chinese['overall-binary-search'] = '整体二分';
	win.tags_chinese['offline'] = '离线';
	win.tags_chinese['nimber'] = 'nimber';
	win.tags_chinese['d-and-c-on-tree'] = '🌳树分治🌳';
	win.tags_chinese['construction'] = '💡构造💡';
	win.tags_chinese['lmoliver'] = '💡明哥题（ad hoc）💡';
	win.tags_chinese['monotonicity-of-decision'] = '决策单调性';
	win.tags_chinese['randomization'] = '🎲随机化🎲';
	win.tags_chinese['interact'] = '交互';
	win.tags_chinese['exc-inc'] = '容斥';
	win.tags_chinese['data-structure'] = '数据结构';
	win.tags_chinese['sqrt-tech'] = '√根号科技√';
	win.tags_chinese['amortized-analysis'] = '均摊分析';
	win.tags_chinese['bijective-proof'] = '双射法';
	win.tags_chinese['writing'] = '⚠正在施工⚠';
	win.tags_chinese['network-flow'] = '🌊网络流🌊';
	win.tags_chinese['safe'] = '😊safe😊';
	win.tags_chinese['euclid'] = '😅euclid😅';
	win.tags_chinese['keter'] = '😱keter😱';
	win.tags_chinese['apollyon'] = '😈apollyon😈';

	win.tags_val={};
	win.tags_val['combinatorics'] = 1;
	win.tags_val['generating-function'] = 2;
	win.tags_val['lagrange-inversion'] = 3;
	win.tags_val['polynomial'] = 4;
	win.tags_val['number-theory'] = 5;
	win.tags_val['min25-sieve'] = 6;
	win.tags_val['calculating-geometry'] = 7;
	win.tags_val['lagrange-interpolation'] = 8;
	win.tags_val['linear-algebra'] = 9;
	win.tags_val['string'] = 10;
	win.tags_val['lyndon-tech'] = 11;
	win.tags_val['linear-programming'] = 12;
	win.tags_val['group-counting'] = 13;
	win.tags_val['game-theory'] = 14;
	win.tags_val['set-power-series'] = 15;
	win.tags_val['pigeon'] = 998244353;
	win.tags_val['young-tableau'] = 17;
	win.tags_val['isotonic-regression'] = 18;
	win.tags_val['overall-binary-search'] = 19;
	win.tags_val['offline'] = 20;
	win.tags_val['nimber'] = 21;
	win.tags_val['d-and-c-on-tree'] = 22;
	win.tags_val['construction'] = 23;
	win.tags_val['lmoliver'] = 24;
	win.tags_val['monotonicity-of-decision'] = 25;
	win.tags_val['randomization'] = 26;
	win.tags_val['interact'] = 27;
	win.tags_val['exc-inc'] = 28;
	win.tags_val['data-structure'] = 29;
	win.tags_val['sqrt-tech'] = 30;
	win.tags_val['amortized-analysis'] = 31;
	win.tags_val['bijective-proof'] = 32;
	win.tags_val['writing'] = 998244354;
	win.tags_val['network-flow'] = 34;
	win.tags_val['safe'] = -58567;
	win.tags_val['euclid'] = -58568;
	win.tags_val['keter'] = -58569;
	win.tags_val['apollyon'] = -58570;

	win.tags_list = [];
	for (var Tag in win.tags_chinese) win.tags_list.push(Tag);
	win.tags_list.sort(function(a, b){ return win.tags_val[a] - win.tags_val[b]});
})(document);